### PR TITLE
Fixed instructions for setting parameters from a table

### PR DESCRIPTION
**Pull request by edwardalee**
This addresses [this comment](https://github.com/lf-lang/lingua-franca/issues/1705#issuecomment-2211359950) about duplicate symbols error occurring when following website instructions to initialize parameters from a table.

The Python version of this fix relies on [PR 2353 in lingua-franca](https://github.com/lf-lang/lingua-franca/pull/2353).

I have updated the version 0.8 docs for the C target only because the Python fix above is not in version 0.8 and the Python code works, albeit inefficiently.  The C code, however, does not compile in version 0.8, so it needed to be fixed.

### CODE REVIEW

**Review by lhstrh — CHANGES_REQUESTED** [review]
We should also make this change for the `0.8.0` docs.

**Comment by edwardalee** [comment]
> We should also make this change for the `0.8.0` docs.

Done with 68f692f4ca673ac19c2b80b8d46f4eb514a5c667

**Review by lhstrh — APPROVED** [review]
